### ISSUE TITLE
Contribute menu items to editor context menu please

### ISSUE THREAD

**Issue by pi1ot** [mitchdenny/ecdc#10]
contributes.menus
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

Currently extension writers can to contribute to:
The Explorer context menu - explorer/context
The editor context menu - editor/context
The editor title menu - editor/title

**Comment by mitchdenny** [comment]
I've added a menu to editor/context - its shipped live now if you want to try it out.
