### ISSUE TITLE
String > HTML Entity Not working for quotes

### ISSUE THREAD

**Issue by PeterXQChen** [mitchdenny/ecdc#11]
It does not encode quotes correctly.

e.g.
“ > `&OpenCurlyDoubleQuote;`
‘ > `&OpenCurlyQuote;`

They should be:
‘ > `&lsquo;`
’ > `&rsquo;`
“ > `&ldquo;`
” > `&rdquo;`

**Comment by mitchdenny** [comment]
Looks like this might be a difference between [HTML5](https://www.w3schools.com/charsets/ref_html_entities_o.asp) and [HTML4](http://www.htmlhelp.com/reference/html40/entities/special.html). Given that we are doing the right thing for HTML5 I don't think it makes sense to support HTML4. However I'm happy to look at a PR which adds support for it under a separate conversion option.
