### ISSUE TITLE
String -> HTML encoding shouldn't encode newlines

### ISSUE THREAD

**Issue by gotofritz** [mitchdenny/ecdc#12]
Hi, thanks for the useful plugin.

I find that on a Mac, when I encode a chunk of HTML into HTML entities all newlines are replaced by `&#10;`. In years of coding I have never found situation where I may need that (if anything, multiple `&nbsp`s may be more useful, although I woudln't want _that_ by default either). Do you think there is a chance to make that configurable on the settings?

Thanks.

**Comment by mitchdenny** [comment]
At the moment the library that I use for doing this doesn't handle encoding newlines gracefully. Do you know of any JavaScript libraries that do this, I could look at swapping them out. I'm using ```ent``` today.

**Comment by gotofritz** [comment]
Hi. This seems to do the job 
https://www.npmjs.com/package/he 

Otherwise there is always the option to run a quick RegExp on the converted text! 😉

**Comment by gotofritz** [comment]
I tried to fork the repo to submit a PR but it cannot run tests:

```
Error: Error: Cannot find module '/Users/gotofritz/work/forks/ecdc/test'
```

**Comment by Lukas238** [comment]
Hi, What is the status of this bug?
Thanks!!

**Comment by mitchdenny** [comment]
Hey sorry I haven't been looking at this repo. @gotofritz did you get the tests running in the end?

**Comment by mitchdenny** [comment]
@gotofritz the ```he``` package looks like a pretty good option actually.

**Comment by tillsanders** [comment]
Hey, I'm having the exact same issue – why was this closed, it's not fixed, is it? 🤔
