### ISSUE TITLE
Add a configration  to select decimal encode for HTML entities

### ISSUE THREAD

**Issue by Lukas238** [mitchdenny/ecdc#13]
I use this plugin to escape html entities in emails, like the smart quotes and the amperstand.

Now, Outlook.com and Outlook app fail to render the _Names HTML Entity_ (```’``` like ```&rsquo;```) but will render fine the _Decimal HTML Entity_ ( ```’``` like ```&#8217;```).

More info here: http://www.fileformat.info/info/unicode/char/2019/index.htm

Can be added a configuration setting for the extencion to define the encoding _type_ (HTML Entity (decimal), HTML Entity (hex), HTML Entity (named))?

Thanks!!

**Comment by mitchdenny** [comment]
Seems like a reasonable ask, I'm not sure if I'll have a chance to get to it in the short term.
