### ISSUE TITLE
Whether you can add Unicode to Chinese, Chinese Unicode ？

### ISSUE THREAD

**Issue by csc-EricWu** [mitchdenny/ecdc#14]
Whether you can add Unicode to Chinese, Chinese Unicode ？

**Comment by mitchdenny** [comment]
Can you provide me an example of what you mean. Do you mean converting from the Chinese characters to HTML entities, or to \uxxxx codes?

**Comment by csc-EricWu** [comment]
![image](https://user-images.githubusercontent.com/13517061/34023254-cff15a2c-e17e-11e7-8ae0-83254cd37f9e.png)
I've seen this feature already
