### ISSUE TITLE
base to string 

### ISSUE THREAD

**Issue by yanglf75** [mitchdenny/ecdc#28]
Sir, ask for help.
I need to put a string to decode（ the string is base64 format），and display it by hex format。But your tool conversion differs from the notepad++ conversion。notepad++ is right for me.
egg.
string is 9PUAQCkAAAEB/gEAAGUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHP9Ps=
your tools convert result is (base64 to string)
3F3F004029000001013F010000650000000000000000000000000000000000000000000000000000000000000000013F3F3F
notepad++ is  (base64 decode)
F4F500402900000101FE01000065000000000000000000000000000000000000000000000000000000000000000001CFF4FB

Can you say why? thank you

**Comment by mitchdenny** [comment]
Closing this since there was no response.
