### ISSUE TITLE
Feature request: encode / decode HTML5 entities

### ISSUE THREAD

**Issue by wmaurer** [mitchdenny/ecdc#3]
It would be great to be also able to encode/decode HTML entities. I thought about writing my own extension for this (I already have published 3), but I feel it might complement yours quite well.

There's a node package that could be used for this:
https://www.npmjs.com/package/ent

What do you think? If you want I could also make a PR with this feature ...

**Comment by mitchdenny** [comment]
Hey @wmaurer - thanks for the idea. I've actually just pushed a really basic implementation of this to master.

**Comment by wmaurer** [comment]
Just installed it and tried it out. Looks good.
Thanks a lot!

**Comment by mitchdenny** [comment]
No worries, if you've got any other ideas feel free to let me know or submit a pull request.

**Comment by wmaurer** [comment]
Just realised that the when encoding a string, the codes come out as numeric. I think for the front-end developer, named codes would be better. node-ent supports this by setting the ops.named to true ...
