### ISSUE TITLE
String / XML conversion Feature

### ISSUE THREAD

**Issue by rudolph-est** [mitchdenny/ecdc#35]
A great feature would be a two-way string / XML conversion. The conversion is a subset of the HTML conversion and would be useful for users who still use (for whatever horrible reason) XML with CDATA tags that contain string-encoded XML.

Some links for reference
https://stackoverflow.com/questions/21758345/what-are-the-official-xml-reserved-characters
https://www.w3.org/TR/xml/#syntax

**Comment by mitchdenny** [comment]
Thanks to @fcharron for this contribution - and thanks for the suggestion @rudolph-est
