### ISSUE TITLE
consider using "encode/decode" for command 

### ISSUE THREAD

**Issue by madansr7** [mitchdenny/ecdc#39]
Great work there! 
I have a suggestion. The extension is called encode/decode which is a suitable name for what it does. However, the execution command "convert selection" is hard to remember. 
how about having an execution command that starts with the name of the extension like "encode/decode: convert selection"? This is a very typical pattern that i've seen with vscode extensions. 
That way you can promote all the sub options, such that they live at the same level.

**Comment by mitchdenny** [comment]
Good suggestion, I'll probably leave the existing one in there since some folks (like me) have muscle memory attached to the old one).

**Comment by mitchdenny** [comment]
This will go out in the 1.2.0 release.
