### ISSUE TITLE
Feature Request: Please add encoder to md5 hexdigest

### ISSUE THREAD

**Issue by 7sDream** [mitchdenny/ecdc#40]
We already have:

`hello world` === md5 base64 ==> `XrY7u+Ae7tCTyyK7j1rNww==`

Cloud you add

`hello world` === md5 hex ==> `5eb63bbbe01eeed093cb22bb8f5acdc3`

as the second format is more commonly used.

**Comment by mitchdenny** [comment]
Thanks for the PR. If you can just rebase it and submit again I'll accept it!
