### ISSUE TITLE
string to html encoding not working

### ISSUE THREAD

**Issue by samthomson** [mitchdenny/ecdc#55]
doesn't work for commas, eg `,`

**Comment by mitchdenny** [comment]
Do you mean the _String to HTML Entities_ conversion?

**Comment by mitchdenny** [comment]
Closing as there has been no follow up.

**Comment by samthomson** [comment]
Sorry, can't remember the menu item text and since removed the extension (as it didn't work for me) so can no longer check.
I wanted the html safe version of `,`, welcome to test yourself :+1:

**Comment by mitchdenny** [comment]
I close this for now because I think it is behaving correctly (or at least as intended). The intent is to replace characters which aren't valid in HTML. A comma is valid, although there is a HTML entity representation.
