### ISSUE TITLE
Does not work a second time

### ISSUE THREAD

**Issue by smlombardi** [mitchdenny/ecdc#57]
1. Select some base64 code.
2. invoke "encode/decode" command
3. in second menu, convert to string
4. edit the string (although this is not necessary, but is the usual workflow)
5. invoke "encode/decode" command

No second menu appears.  Cannot convert.

If I do "developer > reload window" then I can run the command again.  

This has been a bug for a long time, so not dependent on the current version of VSCode, although I am on Version: 1.39.0-insider.

**Comment by mitchdenny** [comment]
Hey @smlombardi I am having trouble reproducing this behavior. How are you invoking the Encode/Decode command?

**Comment by smlombardi** [comment]
Shift-Command-P, then choose it from command palette

**Comment by mitchdenny** [comment]
I'm sorry @smlombardi , I cannot repro this using your instructions. I'm going to close this issue, but if you want to upload a GIF which shows you VSCode window to demonstrate the issue I'll open it up again. I'm using 1.41.1.
