### ISSUE TITLE
XML encoding shouldn't encode em dashes, etc.

### ISSUE THREAD

**Issue by garretwilson** [mitchdenny/ecdc#58]
This seemed like a great tool. But then when I want to encode a string for XML, it encodes things like the em-dash “—” with a character reference. That doesn't break anything but it's pointless. It's 2020, and all our fonts and editors can handle em dash glyphs just fine.

This encoding should only encode things absolutely necessary for XML, such as `&`, `<`, and `>`. In fact I'd like a way to turn off encoding `"` and `'`. (In fact `&apos;` [wasn't even officially supported in HTML 4](https://stackoverflow.com/a/18551371/421049).)

I know this is the XML encoding, not the HTML encoding, but I'd still like to configure which things get converted, and these arbitrary extra characters shouldn't be encoded just because they aren't ASCII. (It might have been appropriate in the 1990s.)

**Comment by mitchdenny** [comment]
Hey @garretwilson, I rely on the [entities](https://www.npmjs.com/package/entities) package on NPM to do this encoding so I'm somewhat limited in what options I can pass in here. I had a quick look at the options to see if there is a way I could explicitly exclude some conversions but there doesn't appear to be a way to do it.

Do you know of a library that provides greater flexibility here?

If there was one that could be found then I'd probably rename the existing command to "strict" and have a new one that does only a subset of the entity encodings. But its contingent on finding a library that can do the heavy lifting.

**Comment by garretwilson** [comment]
Thanks for the reply, @mitchdenny . I'm afraid I don't know much about the JavaScript libraries for dealing with XML. You could always ditch the incomplete libraries and write your own from reading the specifications. That's what I did in Java; see e.g. https://github.com/globalmentor/globalmentor-web/blob/master/xml/src/main/java/com/globalmentor/xml/XMLSerializer.java .

I don't know why it would be hard just to search for the five predefined XML entities and replace them. See [Extensible Markup Language (XML) 1.0 (Fifth Edition) § 4.6 Predefined Entities](https://www.w3.org/TR/xml/#sec-predefined-entl). You shouldn't need a library for that.

Note that what I'm referring to is different from converting to the HTML entities. The XML entities (as I hinted at in the description) are guaranteed to be recognized across all XML and (modern) HTML consumers. The HTML entities (which you are supporting now) are a different thing: a huge list of definitions that aren't even needed with modern editors.

I think you need to step back first and get the definitions straight about what you mean by "entities". I just did a test now to convert the following using "String to XML Entities":

    foo—"bar"

This was converted to the following:

    foo&#x2014;&quot;bar&quot;

First off, `&#x2014;` is not an "entity reference" in XML terminology—it is a ["character reference"](https://www.w3.org/TR/xml/#dt-charref). The only "entity reference" there is `&quot;`.

Secondly, on what basis did you the library convert the em dash (—) to a character reference? Who said that I wanted that converted? There is nothing bad about an em dash. XML doesn't consider it a special character. HTML does not consider it a special character. The _only_ basis that it is something "different" is that it is not ASCII. But who said that I want every non-ASCII character converted to a character reference? Again, we are using modern editors, not editors from 1997.

So when I ask a converter to "convert as string to use XML entities", I expect it to convert [only the XML entities](https://www.w3.org/TR/xml/#sec-predefined-entl). I would expect anyone could easily implement such a replacement using any language. (Be sure to use unit tests, though, to make sure things like `foo&amp;bar` get converted to `foo&amp;amp;bar`, and that you don't doubly encode or encode ampersands in the wrong order, for example.)

**Comment by mitchdenny** [comment]
Version 1.4.0 is going live which includes a fix for this issue.
