### ISSUE TITLE
How to keep new lines

### ISSUE THREAD

**Issue by jd-0001** [mitchdenny/ecdc#62]
I am writing docs and I have to encode HTML for rendering. Now probem is when I convert it to HTML entities all lines are convert in single line.

**Original:**
```
<feather-icon class="mr-1" icon="InfoIcon" />
<feather-icon class="mr-1" icon="HomeIcon" />
<feather-icon class="mr-1" icon="UserIcon" />
<feather-icon icon="TwitterIcon" />
```

**Converted:**
```
&lt;feather-icon class=&quot;mr-1&quot; icon=&quot;InfoIcon&quot; /&gt;&#10;&lt;feather-icon class=&quot;mr-1&quot; icon=&quot;HomeIcon&quot; /&gt;&#10;&lt;feather-icon class=&quot;mr-1&quot; icon=&quot;UserIcon&quot; /&gt;&#10;&lt;feather-icon icon=&quot;TwitterIcon&quot; /&gt;
```

How can I preserve the new lines(\n).

**Comment by mitchdenny** [comment]
You can do this already using editor functionality. Here is how I did it.

1. Select the first line.
2. Use CTRL-ALT-DOWN to select subsequent lines (multi-caret mode).
3. Use conversion function.
