### ISSUE TITLE
Feature Request: Use Encode/Decode instead of "String to" and "to String"

### ISSUE THREAD

**Issue by yrtimiD** [mitchdenny/ecdc#68]
I personally find hard to quick find required command while visually scanning all similarly looking "String to xxx" options.
Can we switch to encode/decode notation instead? (probably can be even configurable to not annoy users used to current schema)

* Encode to Base64
* Decode from Base64
* Encode to JSON Byte Array
* Encode Base64 to JSON Byte Array
* Encode to MD5 Hash (as Base64 or Hex)
* Encode to HTML Entities
* Decode HTML Entities
* Encode to XML Entities
* Decode XML Entities
* Encode to Unicode
* Decode Unicode
* Encode Url
* Decode Url
* Encode Url Component
* Decode Url Component
* Encode Url Component (All Characters)

**Comment by mitchdenny** [comment]
Doesn't really work because some conversions need to specify the input type and the output type so it would just mean you replace <input type> to <output type> with "Encode <input type> to <output type>". At this point I don't plan to make this change.
