### ISSUE TITLE
Feature Request: `yaml` to `json` and `json` to `yaml`

### ISSUE THREAD

**Issue by aldass-snc** [mitchdenny/ecdc#72]
Please add for conversion between `yml`/`yaml` text and `json`.  Since `yaml` is a superset of `json`, there should be a straight-forward-least-common-denominator way to make sure there can be bidirectional conversion.  Even if `yaml` back to `json` may be lossy (i.e. anchors in `yaml`).

**Comment by mitchdenny** [comment]
I've got a basic implementation of this in 1.7.0 of the extension. Give it a try.

**Comment by aldass-snc** [comment]
The _`YAML` to `JSON`_ works well.  The result is a single `JSON` string but, I just use _VSCode_'s document format to pretty-print/format the `JSON`. 

The _`JSON` to `YAML`_ is a bit quirky in that it wraps long text at column ~80 and then uses the `YAML` multi line char (i.e. `>-`) continuation syntax.  When working with `YAML` for _GitHub Actions_ it does require some tweaking after the conversion.  If there was a user setting that could be added to control the wrapping length of YAML text that would help (defaulted to 80).

All in, it get's the job done as I would have expected and is super useful as-is... MUCH THANKS.

**Comment by mitchdenny** [comment]
I haven't come up with a good mechanism for options yet. But in the meantime I can change it not to wrap?

**Comment by aldass-snc** [comment]
Yeah given a choice I'd say to NOT let it wrap and just focus on the conversions... if needed, one can always use their editor's "document format" option to make things look pretty.
