### ISSUE TITLE
The `Encode/Decode: Convert Selection` command does not show up

### ISSUE THREAD

**Issue by cateyes99** [mitchdenny/ecdc#77]
**VSCode version**: 1.67.2
**ecde version**: 1.7.0

Don't know starting from which version, only see the command `extension.subtleConvertSelection`'s `Convert Selection`, but no `extension.convertSelection`'s `Encode/Decode: Convert Selection` on the **VSCode**'s Command Palette, as shown in the sreenshot below.

![image](https://user-images.githubusercontent.com/19678455/169721229-beff9813-5ddc-4ade-be2b-f0db188999df.png)

**Comment by mitchdenny** [comment]
@cateyes99  I'm unable to reproduce this in 1.68.0 is it still an issue for you?

**Comment by cateyes99** [comment]
@mitchdenny cannot reproduce it anymore. we can close it. thx
