### ISSUE TITLE
Extension overrides Polish (Programmers) keyboard layout key binding

### ISSUE THREAD

**Issue by maciejs** [mitchdenny/ecdc#9]
When Polish (Programmers) keyboard layout is used, Ctrl+Alt+C is used to type **ć** character.
Unfortunately, ecdc extension overrides that binding, what interrupts normal typing.

**Comment by mitchdenny** [comment]
Thanks for reporting this. As an interim work around you can change the bindings via your user overrides. Its hard to come up with a unique key binding unfortunately.
